language: go
sudo: false
go:
- 1.16.x
- 1.15.x

env:
- GO111MODULE=on

install:
- go get -t ./...
- go get github.com/mattn/goveralls
- go get github.com/wadey/gocovmerge
- go get -u honnef.co/go/tools/cmd/staticcheck

before_script:
- EXCLUDE_VENDOR=$(go list ./... | grep -v "/vendor/")
- $(exit $(go fmt $EXCLUDE_VENDOR | wc -l))
- go vet $EXCLUDE_VENDOR
# - misspell -error -locale US .
- staticcheck ./...

script:
- if [[ "$TRAVIS_GO_VERSION" =~ 1.13 ]] ; then ./scripts/cov.sh TRAVIS; else go test -v -race -p=1 --failfast ./...; fi
